### ISSUE TITLE
Not same functionality as Sublime

### ISSUE THREAD

**Issue by SandSnip3r** [lyfeyaj/atom-transpose#1]
It seems that Sublime's function only switches and never reverses. Also, the transpose action should be atomically undo-able.
- If no selection region is made (1 or more cursors exist), then each cursor will swap the characters to the left and right and then move the cursor to the right of the right character.
- If one selection region exists (only 1 cursor), nothing happens "Nothing to transpose"
- If two or more selection regions exist (no empty cursors), the selection regions are shifted clockwise. For example, say you have 4 selection regions (1, 2, 3, and 4). The content of 1 is moved to 2, the content of 2 is moved to 3, the content of 3 is moved to 4, and the content of 4 is moved to 1.
- If one or more selection region is selected and one or more empty cursors exist, the empty cursors will select the surrounding word and then act as multiple normal selections.

**Comment by lyfeyaj** [comment]
@SandSnip3r Fixed
